services:
  samba:
    image: dperson/samba:latest
    container_name: samba
    restart: unless-stopped
    environment:
      - TZ=America/Vancouver
    privileged: true  # Required for Bluetooth access
    ports:
      - "137:137/udp"  # NetBIOS name service
      - "138:138/udp"  # NetBIOS datagram service
      - "139:139/tcp"  # NetBIOS session service
      - "445:445/tcp"  # SMB over TCP
    volumes:
      - ./smb.conf:/etc/samba/smb.conf
      - /mnt/raid/backups:/mnt/backups
      - /mnt/raid/documents:/mnt/documents
      - /mnt/raid/media:/mnt/media
    command: >
      -u "samba-user;86C*HzLTnw"