services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    environment:
      - TZ=America/Vancouver
    network_mode: host
    privileged: true  # Required for Bluetooth access
    restart: unless-stopped
    volumes:
      - ./config:/config
      - /run/dbus:/run/dbus  # Add this line for D-Bus support
