services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    environment:
      - TZ=America/Vancouver
    network_mode: host
    privileged: true  # Required for Bluetooth access
    restart: unless-stopped
    volumes:
      - /mnt/raid/apps/homeassistant/config:/config
      - /run/dbus:/run/dbus  # For D-Bus support
      - /mnt/raid/backups/homeassistant:/config/backups  # Map the actual backups folder
