services:
  db:
    image: mariadb:10.11
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - ./db_data:/var/lib/mysql  # Local directory for MariaDB data
    environment:
      - MYSQL_ROOT_PASSWORD=ZuLgWkhWXBLy7UPcU9Ty
      - MYSQL_PASSWORD=6.7JmzNuvphDWyg7
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - ./redis_data:/data  # Local directory for Redis data (optional)

  app:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    depends_on:
      - redis
      - db
    volumes:
      - ./nextcloud_data:/var/www/html  # Local directory for NextCloud files
      #- /mnt/raid/documents:/var/www/html/data/documents  # Mounted documents folder
      #- /mnt/raid/media/photos:/var/www/html/data/photos  # Mounted photos folder
      - ./logs:/var/log  # Local directory for logs
    environment:
      - MYSQL_PASSWORD=6.7JmzNuvphDWyg7
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
