services:
  photoprism:
    image: photoprism/photoprism:arm64
    platform: "linux/arm64"
    ports:
      - "2342:2342"
    environment:
      PHOTOPRISM_DATABASE_DRIVER: "mysql"
      PHOTOPRISM_DATABASE_SERVER: "addon_core_mariadb:3306"
      PHOTOPRISM_DATABASE_NAME: "photoprism"
      PHOTOPRISM_DATABASE_USER: "photoprism"
      PHOTOPRISM_DATABASE_PASSWORD: "your_password"
      PHOTOPRISM_ADMIN_USER: "admin"
      PHOTOPRISM_ADMIN_PASSWORD: "admin_password"
    volumes:
      - "/mnt/data/supervisor/media:/photoprism/originals"  # Example
    networks:
      - hassio
networks:
  hassio:
    external: true

